import type { AssetsManifest } from "pixi.js";

export const manifest: AssetsManifest = {
  bundles: [
    {
      name: "main",
      assets: {
        Belanosima: "./Belanosima.ttf",
        Roboto: "./Roboto.ttf",
        Heart: "./img/heart.png",
        BrokenHeart: "./img/broken-heart.png",
        Checkbox: "./img/ui/checkbox.png",
        CheckboxChecked: "./img/ui/checkboxChecked.png",
        Button: "./img/ui/button.png",
        ButtonPressed: "./img/ui/buttonPressed.png",
        Panel: "./img/ui/panel.png",
        RedCross: "./img/ui/redCross.png",
        AudioOn: "./img/ui/audioOn.png",
        AudioOff: "./img/ui/audioOff.png",
        UIClick: "./sound/uiClick.ogg",
        BtnPressed: "./sound/btnPressed.ogg",
        BtnReleased: "./sound/btnReleased.ogg",
        Buzzer: "./sound/buzzer.ogg",
        Music: "./sound/music.mp3",
        Background: "./img/background.png",
      },
    },
    {
      name: "profiles",
      assets: {
        Profile_Benguigui: "./img/profiles/benguigui.jpg",
        Profile_1: "./img/profiles/1.jpg",
        Profile_2: "./img/profiles/2.jpg",
        Profile_3: "./img/profiles/3.jpg",
        Profile_4: "./img/profiles/4.jpg",
        Profile_5: "./img/profiles/5.jpg",
        Profile_6: "./img/profiles/6.jpg",
        Profile_7: "./img/profiles/7.jpg",
        Profile_8: "./img/profiles/8.jpg",
        Profile_9: "./img/profiles/9.jpg",
        Profile_10: "./img/profiles/10.jpg",
        Profile_11: "./img/profiles/11.jpg",
        Profile_12: "./img/profiles/12.jpg",
        Profile_13: "./img/profiles/13.jpg",
        Profile_14: "./img/profiles/14.jpg",
        Profile_15: "./img/profiles/15.jpg",
        Profile_16: "./img/profiles/16.jpg",
        Profile_17: "./img/profiles/17.jpg",
        Profile_18: "./img/profiles/18.jpg",
        Profile_19: "./img/profiles/19.jpg",
        Profile_20: "./img/profiles/20.jpg",
        Profile_21: "./img/profiles/21.jpg",
      },
    },
  ],
};
